#
# To launch, need to run as sytem:
# oc --as system:admin apply -f deploy/host_network_pod.yaml
#
# After launching, run:
# oc --as system:admin exec -it host-network-demo -c host-network-demo-ctr -- /bin/sh
# ifconfig
# oc --as system:admin exec -it host-network-demo-without -c host-network-demo-without-ctr -- /bin/sh
# ifconfig
#
---
apiVersion: v1
kind: Pod
metadata:
  name: host-network-demo
spec:
  hostNetwork: true
  containers:
    - name: host-network-demo-ctr
      image: busybox
      command: ["sleep", "600"]
---
apiVersion: v1
kind: Pod
metadata:
  name: host-network-demo-without
spec:
  containers:
    - name: host-network-demo-without-ctr
      image: busybox
      command: ["sleep", "600"]
